language: rust
addons:
  apt:
    packages:
      - nasm

script:
    - |
        cargo build --verbose &&
        cargo test --verbose &&
        cargo test --verbose --release --features=decode_test -- --ignored &&
        cargo bench --verbose &&
        cargo doc --verbose
