language: rust
dist: bionic
env:
  - RUST_BACKTRACE=1
addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - zlib1g-dev
      - libdw-dev
      - libiberty-dev
      - ninja-build
      - python3-setuptools
      - python3-pip
      - python3-wheel
      - libsdl2-dev
      - libvulkan-dev
      - ruby # needed by casher on arm64
before_install:
  - export BUILD_DIR="$TRAVIS_HOME/.build"
  - export DEPS_DIR="$TRAVIS_HOME/.local"
  - export ARCH="`uname -m`"
  - mkdir -p "$BUILD_DIR"
  - mkdir -p "$DEPS_DIR/bin"
  - mkdir -p "$DEPS_DIR/lib/pkgconfig"
  - export PATH="$PATH:$DEPS_DIR/bin"
  - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$DEPS_DIR/lib/pkgconfig:$DEPS_DIR/lib/$ARCH-linux-gnu/pkgconfig"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$DEPS_DIR/lib:$DEPS_DIR/lib/$ARCH-linux-gnu"
  - pip3 install meson
  - source "$TRAVIS_BUILD_DIR/.travis/install-sccache.sh"
  - export SCCACHE_CACHE_SIZE=500M
  - export SCCACHE_DIR="$TRAVIS_HOME/.cache/sccache"
  - bash "$TRAVIS_BUILD_DIR/.travis/install-nasm.sh"
  - bash "$TRAVIS_BUILD_DIR/.travis/install-aom.sh"
  - aomenc --help | grep "AV1 Encoder"
  - bash "$TRAVIS_BUILD_DIR/.travis/install-dav1d.sh"
  - dav1d --version
  - cd "$TRAVIS_BUILD_DIR"
cache:
  directories:
    - $TRAVIS_HOME/.cache/sccache
    - $TRAVIS_HOME/.local

after_script:
  - sccache -s

jobs:
  include:
    - name: "Arm build and test"
      rust: stable
      arch: arm64
      script:
        - cargo test --features=decode_test,decode_test_dav1d,quick_test,capi --verbose
